config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount ActionCable.server => '/cable'
  # notify_to :users, with_devise: :users

  root to: 'welcome#index'

  post 'table_config', to: 'table_config#update'

  namespace :my do
    resources :chats do
      member do
        get :messages
        post :add_message
      end
    end

    get '/', to: 'welcome#index'
    get '/messenger', to: 'messenger#index'

    get '/school', to: 'user_groups#school'
    resources :user_groups do
      resources :adverts
    end

    get '/change_password', to: 'welcome#change_password'
    post '/confirm_change_password', to: 'welcome#confirm_change_password'

    resources :users

    resources :notifications do
      member do
        patch 'mark_as_read'
      end
    end
  end

  namespace :multirole do
    get '/', to: 'welcome#index'
  end

  namespace :admin do
    get '/', to: 'welcome#index'
    resources :settings
    resources :subjects
    resources :academic_periods do
      resources :academic_fractions
    end

    get 'schedule', to: 'journals#schedule'
    get 'schedule_generator', to: 'journals#schedule_generator'

    resources :journals do
      resources :journal_fractions do
        member do
          post 'create_lessons'
        end
      end
    end

    resources :lessons

    resources :users do
      collection do
        get 'students'
        get 'teachers'
        get 'custodians'
        get 'admins'
      end
      member do
        post 'reset_password'
      end
      resources :student_profiles
      resources :teacher_profiles
      resources :custodian_profiles
      resources :admin_profiles
    end
    resources :study_groups do
      member do
        post 'assign_student'
        post 'remove_student'

        post 'assign_supervisor'
        post 'remove_supervisor'
      end
      resources :study_sub_groups do
        member do
          post 'assign_student'
          post 'remove_student'
        end
      end
    end

    resources :attachments, only: [:create, :destroy]
  end

  namespace :teacher do
    get '/', to: 'welcome#index'

    get '/teachers_room', to: 'user_groups#teachers_room'
    resources :user_groups do
      resources :adverts
    end

    resources :study_groups do
      collection do
        get 'supervising'
      end
      member do
        get 'passwords'
      end
      resources :adverts
    end
    resources :users
  end

  namespace :student do
    get '/', to: 'welcome#index'
  end

  namespace :no_role do
    get '/', to: 'welcome#index'
  end
end

app/controllers/my/adverts_controller.rb
module My
  class AdvertsController < BaseController

    def create
      klass = params[:advert][:advertable_type].constantize
      @advertable = klass.find(params[:advert][:advertable_id])
      @advert = @advertable.adverts.new(advert_params)
      @advert.author = current_user
      if @advert.save
        @advert.notify :users, key: 'advert.posted', notifier: current_user
        flash[:success] = 'Объявление успешно добавлено'
        redirect_to [:my, @advertable]
      else
        flash[:error] = 'Ошибка добавления объявления'
        redirect_to [:my, @advertable]
      end
    end

    def destroy
      @advert = Advert.find(params[:id])
      @advertable = @advert.advertable
      if @advert.destroy
        flash[:success] = 'Объявление успешно удалено'
        redirect_to [:my, @advertable]
      else
        flash[:error] = 'Ошибка удаления объявления'
        redirect_to [:my, @advertable]
      end
    end

    private

    def advert_params
      params.require(:advert).permit(:advertable_type, :advertable_id, :title, :content, :pinned)
    end
  end
end

app/controllers/my/base_controller.rb
module My
  class BaseController < ApplicationController
    layout 'my'
  end
end

app/controllers/my/chats_controller.rb
module My
  class ChatsController < BaseController
    skip_before_action :verify_authenticity_token
    def messages
      chat = current_user.chats.find(params[:id])
      chat.user_in_chats.find_by_user_id(current_user.id).reset_unread_messages
      render json: chat.messages.order(:created_at)
    end

    def create
      t = CreateChat.new
      result = t.call(u1_id: current_user.id, u2_id: params[:user_id])
      if result.success?
        render json: result.value
      else
        render json: { error: result.value }
      end
    end

    def add_message
      chat = current_user.chats.find(params[:id])
      msg = chat.messages.create(content: params[:content], user_id: current_user.id)
      render json: msg
    end
  end
end

app/controllers/my/messages_controller.rb
module My
  class MessagesController < BaseController
    protect_from_forgery with: :exception

    def create
      @message = Message.new(message_params)
      @message.author_id = current_user.id
      @message.attachment = message_params[:attachment]
      if @message.save!
        # target_chat_member = @message.chat.users.where.not(id: current_user.id).first
        # target_user = User.find(target_chat_member.id)
        ActionCable.server.broadcast("messages_channel_#{@message.chat_id}", send_params)
        update_message_count
      end
      redirect_to my_chats_path(current_chat: @message.chat_id)
    end

    private

    def message_params
      params.require(:message).permit(:content, :chat_id, :user_id, :attachment)
    end

    def send_params
      { chat_id: @message.chat_id,
        message: @message.content,
        sender_avatar_url: current_user.avatar.thumb.url,
        created: l(@message.created_at, format: :short),
        img_attachment: @message&.attachment&.messenger&.url,
        attachment: @message&.attachment&.url,
        attachment_title: @message&.attachment&.file&.filename }
    end

    def update_message_count
      chat_id = @message.chat_id
      user_ids = Chat.find(chat_id).users.where.not(id: @message.author_id).pluck(:id)
      user_ids.each do |u_id|
        total_unread = User.find(u_id).unread_count
        ActionCable.server.broadcast("users_channel_#{u_id}", { chat_id: @message.chat_id, user_id: u_id, total_unread: User.find(u_id).unread_count, message_content: @message.content.truncate(25) })
      end
    end
  end
end

app/controllers/my/messenger_controller.rb
module My
  class MessengerController < BaseController
    def index
      @users = User.not_chating_with(current_user)
      @chats = current_user
        .chats
        .includes(:messages)
        .order_by_relevance
        .map do |chat|
          {
            id: chat.id,
            title: chat.title(current_user), 
            unread: UserInChat.find_by(user_id: current_user.id, chat_id: chat.id).unread_messages,
            last_message: chat.messages.order(:created_at).last.try(:content).try(:truncate, 30) || 'Нет сообщений'
          }
        end
    end
  end
end

app/controllers/my/notifications_controller.rb
module My
  class NotificationsController < BaseController
    def index
      if params[:date]
        start_of_day = Time.parse(params[:date])
        end_of_day = start_of_day.end_of_day
        @notifications = current_user.notifications.where(
          created_at: start_of_day..end_of_day
        )
      else
        @notifications = current_user.notifications.unopened_only
      end
    end

    def mark_as_read
      @notification = current_user.notifications.find(params[:id])
      @id = @notification.id
      if @notification.notifiable
        @notification.open!
      else
        @notification.destroy!
      end
      render 'mark_as_read', layout: false
    end
  end
end

app/controllers/my/user_groups_controller.rb
module My
  class UserGroupsController < BaseController
    def show
      @user_group = UserGroup.find(params[:id])
      if @user_group.system_group?
        redirect_to [:my, @user_group.title.to_sym]
      end
    end

    def school
      @user_group = UserGroup.school
      @adverts = @user_group.adverts.order(created_at: :desc)
    end
  end
end

app/controllers/my/users_controller.rb
module My
  class UsersController < BaseController
    def update
      if current_user.update(user_params)
        flash[:success] = 'Данные успешно обновлены'
      else
        flash[:error] = 'Данные не обновлены'
      end
      redirect_to my_path
    end

    private

    def user_params
      params.require(:user).permit(:avatar)
    end
  end
end

app/controllers/my/welcome_controller.rb
module My
  class WelcomeController < BaseController

    skip_before_action :check_password!, only: [:change_password, :confirm_change_password]

    def index
    end

    def change_password
    end

    def confirm_change_password
      if current_user.update(
        password: params[:password],
        password_confirmation: params[:password_confirmation]
      )
        sign_in(current_user, bypass: true)
        flash[:success] = 'Пароль успешно изменен.'
        redirect_to my_path
      else
        flash[:error] = 'Пароли не совпадают. Попробуйте снова.'
        redirect_to my_change_password_path
      end
    end
  end
end

app/views/my/notifications/_advert.slim
- notifier = notification.notifier.full_name
- notifiable = notification.notifiable
- if notifiable
  p = t("notification.#{notification.key}", advertable: notifiable.advertable.full_title)
  .advert
    h5 = notifiable.title
    = text_to_html(notifiable.content)
    .advert-aside
      .pull-right
        span.time-ago data-val="#{notifiable.created_at}" = notifiable.created_at
      .advert-aside-author
        .advert-aside-author-avatar
          = image_tag(notifiable.author.avatar.thumb.url)
        = notifiable.author.full_name
- else
  p = t("notification.deleted.#{notification.key}")

app/views/my/notifications/index.slim
- header('Уведомления')
- breadcrumb(:my_notifications)
.row
  .col-md-8
    - if params[:date]
      h3 Архив уведомлений
    - else
      h3 Не прочитанные
    - if @notifications.any?
      - @notifications.order(created_at: :desc).each do |n|
        .notification-item id="notification_#{n.id}"
          hr
          - unless n.opened?
            .pull-right
              = link_to 'Не прочитано', mark_as_read_my_notification_path(n), method: :patch, remote: true, class: 'btn btn-sm btn-outline-secondary mark-as-read'
          = render(n.notifiable_type.downcase, notification: n)
    - else
      .alert.alert-warning.text-center
        h2 = fa_icon('bell-o')
        - if params[:date]
          p Не найдено ни одного уведомления за указанный день.
        - else
          p Все уведомления прочитаны. При ностальгии по старым уведомлениям можно воспользоваться архивом.

  .col-md-4
    h3 Архив уведомлений
    .list-group
      = link_to 'Сегодня', [:my, :notifications, date: Date.today], class: "list-group-item list-group-item-action #{params[:date] && Date.parse(params[:date]) == Date.today ? 'active' : nil}"
      = link_to 'Вчера', [:my, :notifications, date: Date.yesterday], class: "list-group-item list-group-item-action #{params[:date] && Date.parse(params[:date]) == Date.yesterday ? 'active' : nil}"
    - if params[:date]
      br
      .list-group
        = link_to 'Показать непрочитанные', [:my, :notifications], class: 'list-group-item list-group-item-action'
      


coffee:
  $('.mark-as-read').on 'mouseover', (e) ->
    $(this).html('Убрать из списка')
  $('.mark-as-read').on 'mouseout', (e) ->
    $(this).html('Не прочитано')

app/views/my/notifications/mark_as_read.js.erb
$("#notification_<%= @id %>").fadeOut('fast');
<% if current_user.notifications.unopened_only.count > 0 %>
  $(".notifications-count").html(<%= current_user.notifications.unopened_only.count %>)
<% else %>
  $(".notifications-count").remove();
<% end %>