config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount ActionCable.server => '/cable'
  # notify_to :users, with_devise: :users

  root to: 'welcome#index'

  post 'table_config', to: 'table_config#update'

  namespace :my do
    resources :chats do
      member do
        get :messages
        post :add_message
      end
    end

    get '/', to: 'welcome#index'
    get '/messenger', to: 'messenger#index'

    get '/school', to: 'user_groups#school'
    resources :user_groups do
      resources :adverts
    end

    get '/change_password', to: 'welcome#change_password'
    post '/confirm_change_password', to: 'welcome#confirm_change_password'

    resources :users

    resources :notifications do
      member do
        patch 'mark_as_read'
      end
    end
  end

  namespace :multirole do
    get '/', to: 'welcome#index'
  end

  namespace :admin do
    get '/', to: 'welcome#index'
    resources :settings
    resources :subjects
    resources :academic_periods do
      resources :academic_fractions
    end

    get 'schedule', to: 'journals#schedule'
    get 'schedule_generator', to: 'journals#schedule_generator'

    resources :journals do
      resources :journal_fractions do
        member do
          post 'create_lessons'
        end
      end
    end

    resources :lessons

    resources :users do
      collection do
        get 'students'
        get 'teachers'
        get 'custodians'
        get 'admins'
      end
      member do
        post 'reset_password'
      end
      resources :student_profiles
      resources :teacher_profiles
      resources :custodian_profiles
      resources :admin_profiles
    end
    resources :study_groups do
      member do
        post 'assign_student'
        post 'remove_student'

        post 'assign_supervisor'
        post 'remove_supervisor'
      end
      resources :study_sub_groups do
        member do
          post 'assign_student'
          post 'remove_student'
        end
      end
    end

    resources :attachments, only: [:create, :destroy]
  end

  namespace :teacher do
    get '/', to: 'welcome#index'

    get '/teachers_room', to: 'user_groups#teachers_room'
    resources :user_groups do
      resources :adverts
    end

    resources :study_groups do
      collection do
        get 'supervising'
      end
      member do
        get 'passwords'
      end
      resources :adverts
    end
    resources :users
  end

  namespace :student do
    get '/', to: 'welcome#index'
  end

  namespace :no_role do
    get '/', to: 'welcome#index'
  end
end

app/views/shared/_topbar.slim
.current-user-bar
  .container
    .pull-right style="line-height: 2.8;"
      .notification-bar
        = link_to my_messenger_path, class: 'btn btn-outline-primary btn-sm' do
          = fa_icon('comment-o')
          - count = current_user.user_in_chats.map(&:unread_messages).reduce(:+) || 0
          - if count > 0
            span.messages-count<
              = count
        span<
        = link_to my_notifications_path, class: 'btn btn-outline-primary btn-sm' do
          = fa_icon('bell-o')
          - if current_user.notifications.unopened_only.count > 0
            span.notifications-count<
              = current_user.notifications.unopened_only.count
    .avatar
      = image_tag(current_user.avatar.thumb)
    b = current_user.full_name
    p
      small = link_to('Моя страница', my_path)
      small< |    
      small = link_to('Выйти', destroy_user_session_path, method: :delete)

nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .container
    a.navbar-brand href='/' = Setting.school_title_short
    button.navbar-toggler aria-controls="navbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavDropdown" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      ul.navbar-nav
        - if current_user.teacher?
          li.nav-item
            = active_link_to 'Страница учителя', teacher_path, class: 'nav-link', active: :exact
          - if current_user.supervising_study_groups.any?
            - if current_user.supervising_study_groups.count > 1
              li.nav-item
                = active_link_to 'Мои классы', supervising_teacher_study_groups_path, class: 'nav-link'
            - else
              li.nav-item
                = active_link_to 'Мой класс', teacher_study_group_path(current_user.supervising_study_groups.last), class: 'nav-link'
          li.nav-item
            = active_link_to 'Мои уроки', supervising_teacher_study_groups_path, class: 'nav-link'
          li.nav-item
            = active_link_to 'Учительская', teacher_teachers_room_path, class: 'nav-link'
        li.nav-item
          = active_link_to 'Моя школа', my_school_path, class: 'nav-link'

- if current_user.admin?
  nav.navbar.navbar-expand-md.navbar-dark style="background-color: #5B5B5B;"
    .container
      = active_link_to admin_path, class: 'navbar-brand', active: :exact do
        = fa_icon('star')
      button.navbar-toggler aria-controls="adminNavbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#adminNavbarNavDropdown" data-toggle="collapse" type="button" 
        span.navbar-toggler-icon
      #adminNavbarNavDropdown.collapse.navbar-collapse
        ul.navbar-nav
          li.nav-item
            = active_link_to 'Настройки', admin_settings_path, class: 'nav-link'
          li.nav-item
            = active_link_to 'Предметы', admin_subjects_path, class: 'nav-link'
          li.nav-item
            = active_link_to 'Календарный план', admin_academic_periods_path, class: 'nav-link'
          li.nav-item
            = active_link_to 'Пользователи', admin_users_path, class: 'nav-link'
          li.nav-item
            = active_link_to 'Классы', admin_study_groups_path, class: 'nav-link'
          li.nav-item
            = active_link_to 'Расписание', admin_schedule_path, class: 'nav-link'