config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount ActionCable.server => '/cable'
  # notify_to :users, with_devise: :users

  root to: 'welcome#index'

  post 'table_config', to: 'table_config#update'

  namespace :my do
    resources :chats do
      member do
        get :messages
        post :add_message
      end
    end

    get '/', to: 'welcome#index'
    get '/messenger', to: 'messenger#index'

    get '/school', to: 'user_groups#school'
    resources :user_groups do
      resources :adverts
    end

    get '/change_password', to: 'welcome#change_password'
    post '/confirm_change_password', to: 'welcome#confirm_change_password'

    resources :users

    resources :notifications do
      member do
        patch 'mark_as_read'
      end
    end
  end

  namespace :multirole do
    get '/', to: 'welcome#index'
  end

  namespace :admin do
    get '/', to: 'welcome#index'
    resources :settings
    resources :subjects
    resources :academic_periods do
      resources :academic_fractions
    end

    get 'schedule', to: 'journals#schedule'
    get 'schedule_generator', to: 'journals#schedule_generator'

    resources :journals do
      resources :journal_fractions do
        member do
          post 'create_lessons'
        end
      end
    end

    resources :lessons

    resources :users do
      collection do
        get 'students'
        get 'teachers'
        get 'custodians'
        get 'admins'
      end
      member do
        post 'reset_password'
      end
      resources :student_profiles
      resources :teacher_profiles
      resources :custodian_profiles
      resources :admin_profiles
    end
    resources :study_groups do
      member do
        post 'assign_student'
        post 'remove_student'

        post 'assign_supervisor'
        post 'remove_supervisor'
      end
      resources :study_sub_groups do
        member do
          post 'assign_student'
          post 'remove_student'
        end
      end
    end

    resources :attachments, only: [:create, :destroy]
  end

  namespace :teacher do
    get '/', to: 'welcome#index'

    get '/teachers_room', to: 'user_groups#teachers_room'
    resources :user_groups do
      resources :adverts
    end

    resources :study_groups do
      collection do
        get 'supervising'
      end
      member do
        get 'passwords'
      end
      resources :adverts
    end
    resources :users
  end

  namespace :student do
    get '/', to: 'welcome#index'
  end

  namespace :no_role do
    get '/', to: 'welcome#index'
  end
end

app/models/study_group.rb
class StudyGroup < ApplicationRecord

  mount_uploader :avatar, AvatarUploader

  has_many :study_group_students
  has_many :students, through: :study_group_students, source: :user

  has_many :study_group_supervisors
  has_many :supervisors, through: :study_group_supervisors, source: :user

  has_many :study_sub_groups

  has_many :adverts, as: :advertable

  has_many :journals, as: :journable

  validates :title, uniqueness: { scope: :level }

  scope :order_by_model, -> { StudyGroup.order_by_classic_model }
  scope :order_by_classic_model, -> { order('level::int', :title) }

  def full_title
    "#{level} #{title}"
  end

  def students_count
    students.count
  end

  def subscribers
    students + supervisors
  end
end

app/controllers/admin/study_groups_controller.rb
module Admin
  class StudyGroupsController < BaseController
    def index
      @table_handler = TableHandler::AdminStudyGroupsIndex.new(current_user.config)
      @q = StudyGroup.ransack(params[:q])
      @study_groups = @q.result.order_by_model.includes(:students)
    end

    def new
      @study_group = StudyGroup.new
    end

    def create
      @study_group = StudyGroup.new(study_group_params)
      if @study_group.save
        redirect_to admin_study_group_path(@study_group)
      else
        render :new
      end
    end

    def show
      @study_group = StudyGroup.find(params[:id])
    end

    def edit
      @study_group = StudyGroup.find(params[:id])
    end

    def update
      @study_group = StudyGroup.find(params[:id])
      if @study_group.update(study_group_params)
        redirect_to admin_study_group_path(@study_group)
      else
        render :edit
      end 
    end

    def assign_student
      transaction = AssignStudentToStudyGroup.new
      result = transaction.call(
        study_group_id: params[:id],
        student_id: params[:user_id]
      )
      if result.success?
        flash[:success] = I18n.t('transactions.success.student_assigned_to_study_group')
        redirect_to admin_study_group_path(params[:id])
      else
        flash[:error] = I18n.t("transactions.error.#{result.value}")
        redirect_to admin_study_group_path(params[:id])
      end
    end

    def remove_student
      transaction = RemoveStudentFromStudyGroup.new
      result = transaction.call(
        study_group_id: params[:id],
        student_id: params[:user_id]
      )
      if result.success?
        flash[:success] = I18n.t('transactions.success.student_removed_from_study_group')
        redirect_to admin_study_group_path(params[:id])
      else
        flash[:error] = I18n.t("transactions.error.#{result.value}")
        redirect_to admin_study_group_path(params[:id])
      end
    end

    def assign_supervisor
      transaction = AssignSupervisorToStudyGroup.new
      result = transaction.call(
        study_group_id: params[:id],
        teacher_id: params[:user_id]
      )
      if result.success?
        flash[:success] = I18n.t('transactions.success.supervisor_assigned_to_study_group')
        redirect_to admin_study_group_path(params[:id])
      else
        flash[:error] = I18n.t("transactions.error.#{result.value}")
        redirect_to admin_study_group_path(params[:id])
      end
    end

    def remove_supervisor
      transaction = RemoveSupervisorFromStudyGroup.new
      result = transaction.call(
        study_group_id: params[:id],
        teacher_id: params[:user_id]
      )
      if result.success?
        flash[:success] = I18n.t('transactions.success.supervisor_removed_from_study_group')
        redirect_to admin_study_group_path(params[:id])
      else
        flash[:error] = I18n.t("transactions.error.#{result.value}")
        redirect_to admin_study_group_path(params[:id])
      end
    end

    private

    def study_group_params
      params.require(:study_group).permit!
    end
  end
end

app/controllers/teacher/study_groups_controller.rb
module Teacher
  class StudyGroupsController < BaseController
    def show
      @study_group = current_user.supervising_study_groups.find(params[:id])
      @adverts = @study_group.adverts.order(created_at: :desc)
    end

    def passwords
      @study_group = current_user.supervising_study_groups.find(params[:id])
      @table_handler = TableHandler::TeacherStudyGroupsPasswords.new(current_user.config)
    end
  end
end

app/views/admin/study_groups/_form.slim
= form_for [:admin, study_group] do |f|
  .row
    .col-md-6
      .form-group
        = form_field(f, :level, :string)
    .col-md-6
      = form_field(f, :title, :string)
  .row
    .col-md-12
      .form-group
        = f.submit 'Сохранить', class: 'btn btn-primary'
        | &nbsp;
        = link_to 'Отмена', :back, class: 'btn btn-secondary'

app/views/admin/study_groups/edit.slim
- breadcrumb :edit_admin_study_group, @study_group
- header('Редактировать класс')
.row
  .col-md-12
    = render('form', study_group: @study_group)

app/views/admin/study_groups/index.slim
- breadcrumb :admin_study_groups
- header('Классы')
- links([['Добавить учебный класс', new_admin_study_group_path]])
= configurable_table(collection: @study_groups, table_handler: @table_handler, q: @q)

app/views/admin/study_groups/new.slim
- breadcrumb :new_admin_study_group
- header('Добавить класс')
.row
  .col-md-12
    = render('form', study_group: @study_group)

app/views/admin/study_groups/show.slim
- breadcrumb :admin_study_group, @study_group
- header(@study_group.full_title)
.row
  .col-md-4
    = link_to edit_admin_study_group_path(@study_group), class: 'btn btn-primary float-right' do
      = fa_icon('pencil')
    h3 Детали класса
    = data_set(@study_group, :level, :string)
    = data_set(@study_group, :title, :string)
    = data_set(@study_group, :students_count, :string)
    br
    = link_to [:new, :admin, @study_group, :study_sub_group], class: 'btn btn-primary float-right' do
        = fa_icon('plus')
    h3 Группы
    - if @study_group.study_sub_groups.any?
      - @study_group.study_sub_groups.each do |sub_group|
        .data-set
          b = sub_group.title
          p
            - students_count = t('student', count: sub_group.students_count)
            small = students_count
            small< | 
            small = link_to 'Перейти', [:admin, @study_group, sub_group]
    - else
      br
      .alert.alert-warning.text-center
        h2 = fa_icon('group')
        p В этом классе нет разделения на учебные группы. Добавьте, если по некоторым из предметов ученики делятся на группы.

  .col-md-4
    = react_component('AssignUserToStudyGroup', { study_group_id: @study_group.id, users: User.students_without_study_group.alphabetical_order })
    h3 Ученики
    - if @study_group.students.any?
      - @study_group.students.alphabetical_order.each do |u|
        .user-in-list
          .user-avatar-in-list
            = image_tag(u.avatar.thumb)
          = u.full_name
          p
            small = link_to 'Перейти', admin_user_path(u)
            small< |
            small< = link_to 'Убрать из класса', remove_student_admin_study_group_path(@study_group, user_id: u.id), method: :post, data: {confirm: 'Вы уверены?' }
    - else
      br
      .alert.alert-warning.text-center
        h2 = fa_icon('coffee')
        p В этом классе некого учить. Преподаватели могут расслабиться за чашечкой кофе.


  .col-md-4
    = react_component('AssignSupervisorToStudyGroup', { study_group_id: @study_group.id, users: User.teachers.alphabetical_order })
    h3 Классное руководство
    - if @study_group.supervisors.any?
      - @study_group.supervisors.alphabetical_order.each do |u|
        .user-in-list
          .user-avatar-in-list
            = image_tag(u.avatar.thumb)
          = u.full_name
          p
            small = link_to 'Перейти', admin_user_path(u)
            small< |
            small< = link_to 'Снять с руководства', remove_supervisor_admin_study_group_path(@study_group, user_id: u.id), method: :post, data: {confirm: 'Вы уверены?' }
    - else
      br
      .alert.alert-warning.text-center
        h2 = fa_icon('bomb')
        p В этом классе нет руководителя. Следует назначить во избежание начала анархии.