config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  mount ActionCable.server => '/cable'
  # notify_to :users, with_devise: :users

  root to: 'welcome#index'

  post 'table_config', to: 'table_config#update'

  namespace :my do
    resources :chats do
      member do
        get :messages
        post :add_message
      end
    end

    get '/', to: 'welcome#index'
    get '/messenger', to: 'messenger#index'

    get '/school', to: 'user_groups#school'
    resources :user_groups do
      resources :adverts
    end

    get '/change_password', to: 'welcome#change_password'
    post '/confirm_change_password', to: 'welcome#confirm_change_password'

    resources :users

    resources :notifications do
      member do
        patch 'mark_as_read'
      end
    end
  end

  namespace :multirole do
    get '/', to: 'welcome#index'
  end

  namespace :admin do
    get '/', to: 'welcome#index'
    resources :settings
    resources :subjects
    resources :academic_periods do
      resources :academic_fractions
    end

    get 'schedule', to: 'journals#schedule'
    get 'schedule_generator', to: 'journals#schedule_generator'

    resources :journals do
      resources :journal_fractions do
        member do
          post 'create_lessons'
        end
      end
    end

    resources :lessons

    resources :users do
      collection do
        get 'students'
        get 'teachers'
        get 'custodians'
        get 'admins'
      end
      member do
        post 'reset_password'
      end
      resources :student_profiles
      resources :teacher_profiles
      resources :custodian_profiles
      resources :admin_profiles
    end
    resources :study_groups do
      member do
        post 'assign_student'
        post 'remove_student'

        post 'assign_supervisor'
        post 'remove_supervisor'
      end
      resources :study_sub_groups do
        member do
          post 'assign_student'
          post 'remove_student'
        end
      end
    end

    resources :attachments, only: [:create, :destroy]
  end

  namespace :teacher do
    get '/', to: 'welcome#index'

    get '/teachers_room', to: 'user_groups#teachers_room'
    resources :user_groups do
      resources :adverts
    end

    resources :study_groups do
      collection do
        get 'supervising'
      end
      member do
        get 'passwords'
      end
      resources :adverts
    end
    resources :users
  end

  namespace :student do
    get '/', to: 'welcome#index'
  end

  namespace :no_role do
    get '/', to: 'welcome#index'
  end
end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
end

app/controllers/admin/student_profiles_controller.rb
module Admin
  class StudentProfilesController < BaseController
    def create
      @user = User.find(params[:user_id])
      @deleted_student_profile = StudentProfile.only_deleted.find_by_user_id(@user.id)
      if @deleted_student_profile
        @deleted_student_profile.restore
      else
        @student_profile = StudentProfile.new(user_id: @user.id)
        @student_profile.save
      end
      redirect_to admin_user_path(@user)
    end

    def edit
      @user = User.find(params[:user_id])
      @student_profile = StudentProfile.find_by(id: params[:id], user_id: @user.id)
    end

    def update
      @user = User.find(params[:user_id])
      @student_profile = StudentProfile.find_by(id: params[:id], user_id: @user.id)
      if @student_profile.update(student_profile_params)
        redirect_to admin_user_path(@user)
      else
        render :edit
      end
    end

    def destroy
      @user = User.find(params[:user_id])
      @student_profile = StudentProfile.find_by(id: params[:id], user_id: @user.id)
      if @user.study_group
        flash[:error] = "Ученик привязан к #{@user.study_group.full_title} классу. Сначала уберите ученика из класса."
        redirect_to admin_user_path(@user)
      else
        @student_profile.destroy
        flash[:success] = 'Пользователь больше не является учеником'
        redirect_to admin_user_path(@user)
      end
    end

    def student_profile_params
      params.require(:student_profile).permit!
    end
  end
end

app/views/admin/student_profiles/_card.slim
- if user.student?
  .card.bg-light.mb-3
    .card-header Является учеником
    .card-body
      p.card-text Этот пользователь является учеником и может быть привязан к учебным классам.
      p.card-text
        = link_to 'Убрать роль ученика', admin_user_student_profile_path(user.student_profile, user_id: user.id), method: 'DELETE', class: 'btn btn-block btn-outline-danger'
      - if user.study_group
        = link_to "Учится в #{user.study_group.full_title} классе", admin_study_group_path(user.study_group), class: 'btn btn-block btn-outline-success' 
- else
  .card.bg-light.mb-3
    .card-header Не является учеником
    .card-body
      p.card-text Этот пользователь не является учеником и не может быть привязан к учебным классам.
      p.card-text
        = link_to 'Назначить учеником', admin_user_student_profiles_path(user_id: user.id), method: 'POST', class: 'btn btn-block btn-outline-success'

app/views/admin/student_profiles/_data_set.slim
- if user.student_profile
  = link_to edit_admin_user_student_profile_path(user.student_profile, user_id: user), class: 'btn btn-primary float-right' do
    = fa_icon('pencil')
  h3 Анкета ученика
  - student_profile = user.student_profile
  = data_set(student_profile, :created_at, :datetime)
  = data_set(student_profile, :updated_at, :datetime)
  = data_set(student_profile, :date_of_admission, :date)
  br/

app/views/admin/student_profiles/_form.slim
= form_for [:admin, student_profile.user, student_profile] do |f|
  .row
    .col-md-12
      = form_field(f, :date_of_admission, :date)
  .row
    .col-md-12
      .form-group
        = f.submit 'Сохранить', class: 'btn btn-primary'
        | &nbsp;
        = link_to 'Отмена', :back, class: 'btn btn-secondary'

app/views/admin/student_profiles/edit.slim
- breadcrumb :admin_user_student_profile_edit, @user, @student_profile
- header('Редактировать анкету ученика')
.row
  .col-md-12
    = render('form', student_profile: @student_profile)